### ISSUE TITLE
mono 4.0.x build failure

### ISSUE THREAD

**Issue by Narrat** [meebey/db4o-net#1]
I'm posting this here instead of the smuxi-repo, because building failed for this dir

> :  warning : Default tasks file /usr/lib/mono/3.5/Microsoft.Common.tasks not found, ignoring.
> ./db4o-net/Db4objects.Db4o/Db4objects.Db4o-2008.csproj: error : /home/omnius/Builds/Maint/AUR4/smuxi-git/src/smuxi/lib/db4o-net/Db4objects.Db4o/Db4objects.Db4o-2008.csproj: /home/omnius/Builds/Maint/AUR4/smuxi-git/src/smuxi/lib/db4o-net/Db4objects.Db4o/Db4objects.Db4o-2008.csproj could not import "$(MSBuildBinPath)\Microsoft.CSharp.targets"
> Build FAILED.
> 
> Warnings:
> 
> :  warning : Default tasks file /usr/lib/mono/3.5/Microsoft.Common.tasks not found, ignoring.
> 
> Errors:
> 
> ./db4o-net/Db4objects.Db4o/Db4objects.Db4o-2008.csproj: error : /home/omnius/Builds/Maint/AUR4/smuxi-git/src/smuxi/lib/db4o-net/Db4objects.Db4o/Db4objects.Db4o-2008.csproj: /home/omnius/Builds/Maint/AUR4/smuxi-git/src/smuxi/lib/db4o-net/Db4objects.Db4o/Db4objects.Db4o-2008.csproj could not import "$(MSBuildBinPath)\Microsoft.CSharp.targets"
> 
>    1 Warning(s)
>    1 Error(s)
> 
> Time Elapsed 00:00:00.9161880
> Makefile:982: die Regel für Ziel „../bin/debug/Db4objects.Db4o.dll“ scheiterte
> make[2]: **\* [../bin/debug/Db4objects.Db4o.dll] Fehler 1
> make[2]: Verzeichnis „/home/omnius/Builds/Maint/AUR4/smuxi-git/src/smuxi/lib“ wird verlassen
> Makefile:738: die Regel für Ziel „all-recursive“ scheiterte
> make[1]: **\* [all-recursive] Fehler 1
> make[1]: Verzeichnis „/home/omnius/Builds/Maint/AUR4/smuxi-git/src/smuxi/lib“ wird verlassen
> Makefile:651: die Regel für Ziel „all-recursive“ scheiterte
> make: **\* [all-recursive] Fehler 1

**Comment by meebey** [comment]
Db4objects.Db4o-2008.csproj could not import "$(MSBuildBinPath)\Microsoft.CSharp.targets"
Build FAILED.

That sounds like something is missing of mono-xbuild or msbuild. See if you can find that file somewhere.

**Comment by meebey** [comment]
Please check http://stackoverflow.com/questions/28652888/error-csproj-could-not-import-msbuildbinpath-microsoft-csharp-targets-on

But maybe it is the Windowsism of \ instead of  / in paths. Not sure if Mono 4.0 has replaced their xbuild impl which could lead to Unix specific regressions.

**Comment by Narrat** [comment]
At least the files are there (so it seems)

> usr/lib/mono/4.5/Microsoft.CSharp.targets
> usr/lib/mono/xbuild/12.0/bin/Microsoft.CSharp.targets
> usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets

Need to check the second thing

Edit: If you want to look at the file list
https://www.archlinux.org/packages/extra/i686/mono/files/

**Comment by Narrat** [comment]
How shall I find the right project file? :D 

> $ xbuild /verbosity:normal
> MSBUILD: error MSBUILD0005: Please specify the project or solution file to build, as more than one solution or project file was found in the current directory

Current directory is 

> smuxi/lib/db4o-net

**Comment by meebey** [comment]
It's in the error message:
./db4o-net/Db4objects.Db4o/Db4objects.Db4o-2008.csproj

**Comment by Narrat** [comment]
_cough_
Read first, then ask...

> $ xbuild /verbosity:diagnostic Db4objects.Db4o/Db4objects.Db4o-2008.csproj
> XBuild Engine Version 12.0
> Mono, Version 4.0.1.0
> Copyright (C) 2005-2013 Various Mono authors
> Loading default tasks for ToolsVersion: 4.0 from /usr/lib/mono/4.5/Microsoft.Common.tasks
> 
> Build started 22.05.2015 18:06:53.
> 
> ---
> 
> Loading default tasks for ToolsVersion: 3.5 from /usr/lib/mono/3.5/Microsoft.Common.tasks
> :  warning : Default tasks file /usr/lib/mono/3.5/Microsoft.Common.tasks not found, ignoring.
> Db4objects.Db4o/Db4objects.Db4o-2008.csproj: error : /home/omnius/Builds/Maint/AUR4/smuxi-git/src/smuxi/lib/db4o-net/Db4objects.Db4o/Db4objects.Db4o-2008.csproj: /home/omnius/Builds/Maint/AUR4/smuxi-git/src/smuxi/lib/db4o-net/Db4objects.Db4o/Db4objects.Db4o-2008.csproj could not import "$(MSBuildBinPath)\Microsoft.CSharp.targets"
> Db4objects.Db4o/Db4objects.Db4o-2008.csproj: Microsoft.Build.BuildEngine.InvalidProjectFileException: /home/omnius/Builds/Maint/AUR4/smuxi-git/src/smuxi/lib/db4o-net/Db4objects.Db4o/Db4objects.Db4o-2008.csproj: /home/omnius/Builds/Maint/AUR4/smuxi-git/src/smuxi/lib/db4o-net/Db4objects.Db4o/Db4objects.Db4o-2008.csproj could not import "$(MSBuildBinPath)\Microsoft.CSharp.targets" ---> Microsoft.Build.BuildEngine.InvalidProjectFileException: /home/omnius/Builds/Maint/AUR4/smuxi-git/src/smuxi/lib/db4o-net/Db4objects.Db4o/Db4objects.Db4o-2008.csproj could not import "$(MSBuildBinPath)\Microsoft.CSharp.targets"
>   at Microsoft.Build.BuildEngine.Import.ForEachExtensionPathTillFound (System.Xml.XmlElement xmlElement, Microsoft.Build.BuildEngine.Project project, Microsoft.Build.BuildEngine.ImportedProject importingProject, System.Func`3 func) [0x00000] in <filename unknown>:0 
>   at Microsoft.Build.BuildEngine.Project.AddImport (System.Xml.XmlElement xmlElement, Microsoft.Build.BuildEngine.ImportedProject importingProject, Boolean evaluate_properties) [0x00000] in <filename unknown>:0 
>   at Microsoft.Build.BuildEngine.Project.ProcessElements (System.Xml.XmlElement rootElement, Microsoft.Build.BuildEngine.ImportedProject ip) [0x00000] in <filename unknown>:0 
>   at Microsoft.Build.BuildEngine.Project.ProcessXml () [0x00000] in <filename unknown>:0 
>   at Microsoft.Build.BuildEngine.Project.DoLoad (System.IO.TextReader textReader) [0x00000] in <filename unknown>:0 
>   --- End of inner exception stack trace ---
>   at Microsoft.Build.BuildEngine.Project.DoLoad (System.IO.TextReader textReader) [0x00000] in <filename unknown>:0 
>   at Microsoft.Build.BuildEngine.Project.Load (System.String projectFileName, ProjectLoadSettings settings) [0x00000] in <filename unknown>:0 
>   at Microsoft.Build.BuildEngine.Project.Load (System.String projectFileName) [0x00000] in <filename unknown>:0 
>   at Microsoft.Build.BuildEngine.Engine.BuildProjectFileInternal (System.String projectFile, System.String[] targetNames, Microsoft.Build.BuildEngine.BuildPropertyGroup globalProperties, IDictionary targetOutputs, BuildSettings buildFlags, System.String toolsVersion) [0x00000] in <filename unknown>:0 
>   at Microsoft.Build.BuildEngine.Engine.BuildProjectFile (System.String projectFile, System.String[] targetNames, Microsoft.Build.BuildEngine.BuildPropertyGroup globalProperties, IDictionary targetOutputs, BuildSettings buildFlags, System.String toolsVersion) [0x00000] in <filename unknown>:0 
> Target perfomance summary:
> 
> Tasks perfomance summary:
> 
> Build FAILED.
> 
> Warnings:
> 
> :  warning : Default tasks file /usr/lib/mono/3.5/Microsoft.Common.tasks not found, ignoring.
> 
> Errors:
> 
> Db4objects.Db4o/Db4objects.Db4o-2008.csproj: error : /home/omnius/Builds/Maint/AUR4/smuxi-git/src/smuxi/lib/db4o-net/Db4objects.Db4o/Db4objects.Db4o-2008.csproj: /home/omnius/Builds/Maint/AUR4/smuxi-git/src/smuxi/lib/db4o-net/Db4objects.Db4o/Db4objects.Db4o-2008.csproj could not import "$(MSBuildBinPath)\Microsoft.CSharp.targets"
> 
>    1 Warning(s)
>      1 Error(s)
> 
> Time Elapsed 00:00:00.2205070

Not wiser at all after that

**Comment by meebey** [comment]
Good news, Smuxi 0.11.1 builds on Mono 4.x with this patch applied:
http://paste.opensuse.org/85181744

**Comment by Narrat** [comment]
Sweet. I will add this to the AUR-package

**Comment by meebey** [comment]
Fixed in c81dbd1590cef5229ed39adc45d52cc5f5f481aa
